<Project>

  <PropertyGroup>
    <DefaultTargetFramework>net9.0</DefaultTargetFramework>
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)ProtonDrive.ruleset</CodeAnalysisRuleSet>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <Product>Proton Drive</Product>
    <Company>Proton AG</Company>
    <Version>1.12.12</Version>

    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <Deterministic>true</Deterministic>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <Using Include="Xunit" />
    <Using Include="AwesomeAssertions" />
    <Using Include="NSubstitute" />
  </ItemGroup>

</Project>
