//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtonDrive.App.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtonDrive.App.Windows.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccountDisplayStatus_val_AccountError {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in.
        /// </summary>
        internal static string AccountDisplayStatus_val_SessionError {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_SessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up....
        /// </summary>
        internal static string AccountDisplayStatus_val_SettingUp {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_SettingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed out.
        /// </summary>
        internal static string AccountDisplayStatus_val_SignedOut {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_SignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string AccountDisplayStatus_val_SigningIn {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out....
        /// </summary>
        internal static string AccountDisplayStatus_val_SigningOut {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_SigningOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in.
        /// </summary>
        internal static string AccountDisplayStatus_val_Succeeded {
            get {
                return ResourceManager.GetString("AccountDisplayStatus_val_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to switch account. Restart the app..
        /// </summary>
        internal static string AccountErrorCode_val_AccountSwitchingFailed {
            get {
                return ResourceManager.GetString("AccountErrorCode_val_AccountSwitchingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has unpaid invoices. Go to your dashboard to pay or let your admin know..
        /// </summary>
        internal static string AccountErrorCode_val_Delinquent {
            get {
                return ResourceManager.GetString("AccountErrorCode_val_Delinquent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t connect to Proton Drive. Try checking your internet connection..
        /// </summary>
        internal static string AccountErrorCode_val_DriveAccessFailed {
            get {
                return ResourceManager.GetString("AccountErrorCode_val_DriveAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access Proton Drive, upgrade your plan.
        /// </summary>
        internal static string AccountErrorCode_val_NoDriveAccess {
            get {
                return ResourceManager.GetString("AccountErrorCode_val_NoDriveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccountErrorCode_val_None {
            get {
                return ResourceManager.GetString("AccountErrorCode_val_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_Create {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_Delete {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_Download {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching updates.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_FetchUpdates {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_FetchUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moving.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_Move {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renaming.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_Rename {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading.
        /// </summary>
        internal static string Activity_InProgress_SyncActivityType_val_Upload {
            get {
                return ResourceManager.GetString("Activity_InProgress_SyncActivityType_val_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_Create {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_Delete {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_Download {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates fetched.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_FetchUpdates {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_FetchUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moved.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_Move {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renamed.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_Rename {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded.
        /// </summary>
        internal static string Activity_Succeeded_SyncActivityType_val_Upload {
            get {
                return ResourceManager.GetString("Activity_Succeeded_SyncActivityType_val_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set up an account.
        /// </summary>
        internal static string AppDisplayStatus_val_AccountError {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing up....
        /// </summary>
        internal static string AppDisplayStatus_val_FinishingUp {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_FinishingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string AppDisplayStatus_val_Offline {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up....
        /// </summary>
        internal static string AppDisplayStatus_val_SettingUp {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SettingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed out.
        /// </summary>
        internal static string AppDisplayStatus_val_SignedOut {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in.
        /// </summary>
        internal static string AppDisplayStatus_val_SignInError {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SignInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string AppDisplayStatus_val_SigningIn {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out....
        /// </summary>
        internal static string AppDisplayStatus_val_SigningOut {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SigningOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set up sync folders.
        /// </summary>
        internal static string AppDisplayStatus_val_SyncFolderError {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SyncFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed.
        /// </summary>
        internal static string AppDisplayStatus_val_SynchronizationError {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SynchronizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization paused.
        /// </summary>
        internal static string AppDisplayStatus_val_SynchronizationPaused {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SynchronizationPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some items failed to synchronize.
        /// </summary>
        internal static string AppDisplayStatus_val_SynchronizationWarning {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_SynchronizationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        internal static string AppDisplayStatus_val_Synchronized {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_Synchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        internal static string AppDisplayStatus_val_Synchronizing {
            get {
                return ResourceManager.GetString("AppDisplayStatus_val_Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string FileSystemErrorCode_val_Cancelled {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path.
        /// </summary>
        internal static string FileSystemErrorCode_val_DirectoryNotFound {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already in use.
        /// </summary>
        internal static string FileSystemErrorCode_val_DuplicateName {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space.
        /// </summary>
        internal static string FileSystemErrorCode_val_FreeSpaceExceeded {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_FreeSpaceExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder has diverged.
        /// </summary>
        internal static string FileSystemErrorCode_val_IdentityMismatch {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_IdentityMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of data failed.
        /// </summary>
        internal static string FileSystemErrorCode_val_IntegrityFailure {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_IntegrityFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not valid.
        /// </summary>
        internal static string FileSystemErrorCode_val_InvalidName {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File skipped because it has changed too recently. App will retry automatically.
        /// </summary>
        internal static string FileSystemErrorCode_val_LastWriteTimeTooRecent {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_LastWriteTimeTooRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder has diverged.
        /// </summary>
        internal static string FileSystemErrorCode_val_MetadataMismatch {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_MetadataMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder does not exist.
        /// </summary>
        internal static string FileSystemErrorCode_val_ObjectNotFound {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string FileSystemErrorCode_val_Offline {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not available locally and cannot be uploaded. To resolve, please delete it and restore a copy from the Proton Drive trash if available..
        /// </summary>
        internal static string FileSystemErrorCode_val_Partial {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder does not exist.
        /// </summary>
        internal static string FileSystemErrorCode_val_PathNotFound {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder is being used by another app.
        /// </summary>
        internal static string FileSystemErrorCode_val_SharingViolation {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_SharingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        internal static string FileSystemErrorCode_val_TimedOut {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload aborted because file changed during sync. App will retry automatically.
        /// </summary>
        internal static string FileSystemErrorCode_val_TransferAbortedDueToFileChange {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_TransferAbortedDueToFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough permissions.
        /// </summary>
        internal static string FileSystemErrorCode_val_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string FileSystemErrorCode_val_Unknown {
            get {
                return ResourceManager.GetString("FileSystemErrorCode_val_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to Proton Drive. Try checking your internet connection..
        /// </summary>
        internal static string MappingErrorCode_val_DriveAccessFailed {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_DriveAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proton Drive device folder has been moved. Set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_DriveFolderDiverged {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_DriveFolderDiverged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t access your Proton Drive files, possibly due to a device folder deletion. Set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_DriveFolderDoesNotExist {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_DriveFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t access your Proton Drive files, possibly due to a device deletion. Set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_DriveHostDeviceDiverged {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_DriveHostDeviceDiverged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access your Proton Drive files, possibly due to a password reset. Set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_DriveShareDiverged {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_DriveShareDiverged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t access your Proton Drive files, possibly due to a password reset. Set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_DriveVolumeDiverged {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_DriveVolumeDiverged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free up space or deselect the checkbox..
        /// </summary>
        internal static string MappingErrorCode_val_InsufficientLocalFreeSpace {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_InsufficientLocalFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up a sync folder requires an empty Windows or Proton Drive web folder. Please clear one and try again..
        /// </summary>
        internal static string MappingErrorCode_val_LocalAndRemoteFoldersNotEmpty {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalAndRemoteFoldersNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync file not found. It may have been deleted, renamed, or moved. Restore it or set it up again..
        /// </summary>
        internal static string MappingErrorCode_val_LocalFileDoesNotExist {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access or create local sync folder. We’ll keep retrying..
        /// </summary>
        internal static string MappingErrorCode_val_LocalFileSystemAccessFailed {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFileSystemAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync folder was replaced by a new folder in path. Restore the previous sync folder or set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_LocalFolderDiverged {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFolderDiverged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync folder not found. It may have been deleted, renamed, or moved. Restore it or set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_LocalFolderDoesNotExist {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is included by an already synced folder.
        /// </summary>
        internal static string MappingErrorCode_val_LocalFolderIncludedByAnAlreadySyncedFolder {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFolderIncludedByAnAlreadySyncedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder contains an already synced folder.
        /// </summary>
        internal static string MappingErrorCode_val_LocalFolderIncludesAnAlreadySyncedFolder {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFolderIncludesAnAlreadySyncedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local folder is not eligible for synchronization. Set up a new sync folder..
        /// </summary>
        internal static string MappingErrorCode_val_LocalFolderNonSyncable {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFolderNonSyncable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local folder must be empty before setting up sync.
        /// </summary>
        internal static string MappingErrorCode_val_LocalFolderNotEmpty {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalFolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported local drive type. Try setting up sync folder on a different local drive..
        /// </summary>
        internal static string MappingErrorCode_val_LocalVolumeNotSupported {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_LocalVolumeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MappingErrorCode_val_None {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing is temporarily unavailable.
        /// </summary>
        internal static string MappingErrorCode_val_SharingDisabled {
            get {
                return ResourceManager.GetString("MappingErrorCode_val_SharingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set up sync folders.
        /// </summary>
        internal static string MappingSetupStatus_val_Failed {
            get {
                return ResourceManager.GetString("MappingSetupStatus_val_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MappingSetupStatus_val_None {
            get {
                return ResourceManager.GetString("MappingSetupStatus_val_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set up some sync folders.
        /// </summary>
        internal static string MappingSetupStatus_val_PartiallySucceeded {
            get {
                return ResourceManager.GetString("MappingSetupStatus_val_PartiallySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up sync folders....
        /// </summary>
        internal static string MappingSetupStatus_val_SettingUp {
            get {
                return ResourceManager.GetString("MappingSetupStatus_val_SettingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MappingSetupStatus_val_Succeeded {
            get {
                return ResourceManager.GetString("MappingSetupStatus_val_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Features.
        /// </summary>
        internal static string ReleaseNoteType_val_Feature {
            get {
                return ResourceManager.GetString("ReleaseNoteType_val_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Fixes.
        /// </summary>
        internal static string ReleaseNoteType_val_Fix {
            get {
                return ResourceManager.GetString("ReleaseNoteType_val_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvements.
        /// </summary>
        internal static string ReleaseNoteType_val_Improvement {
            get {
                return ResourceManager.GetString("ReleaseNoteType_val_Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out....
        /// </summary>
        internal static string SessionStatus_val_Ending {
            get {
                return ResourceManager.GetString("SessionStatus_val_Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in failed. Try checking your internet connection..
        /// </summary>
        internal static string SessionStatus_val_Failed {
            get {
                return ResourceManager.GetString("SessionStatus_val_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed out.
        /// </summary>
        internal static string SessionStatus_val_NotStarted {
            get {
                return ResourceManager.GetString("SessionStatus_val_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SessionStatus_val_SigningIn {
            get {
                return ResourceManager.GetString("SessionStatus_val_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in.
        /// </summary>
        internal static string SessionStatus_val_Started {
            get {
                return ResourceManager.GetString("SessionStatus_val_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SessionStatus_val_Starting {
            get {
                return ResourceManager.GetString("SessionStatus_val_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space on this device.
        /// </summary>
        internal static string SyncFolderValidationResult_ttl_InsufficientLocalFreeSpace {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_ttl_InsufficientLocalFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder is included by an already synced folder.
        /// </summary>
        internal static string SyncFolderValidationResult_val_FolderIncludedByAnAlreadySyncedFolder {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_FolderIncludedByAnAlreadySyncedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder contains an already synced folder.
        /// </summary>
        internal static string SyncFolderValidationResult_val_FolderIncludesAnAlreadySyncedFolder {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_FolderIncludesAnAlreadySyncedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free up space or deselect the checkbox..
        /// </summary>
        internal static string SyncFolderValidationResult_val_InsufficientLocalFreeSpace {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_InsufficientLocalFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be found.
        /// </summary>
        internal static string SyncFolderValidationResult_val_LocalFileDoesNotExist {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_LocalFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access the folder.
        /// </summary>
        internal static string SyncFolderValidationResult_val_LocalFileSystemAccessFailed {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_LocalFileSystemAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder cannot be found.
        /// </summary>
        internal static string SyncFolderValidationResult_val_LocalFolderDoesNotExist {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_LocalFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder must be empty before setting up sync.
        /// </summary>
        internal static string SyncFolderValidationResult_val_LocalFolderNotEmpty {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_LocalFolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported drive type.
        /// </summary>
        internal static string SyncFolderValidationResult_val_LocalVolumeNotSupported {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_LocalVolumeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing folders from network drives is not supported.
        /// </summary>
        internal static string SyncFolderValidationResult_val_NetworkFolderNotSupported {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_NetworkFolderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder is not eligible for sync.
        /// </summary>
        internal static string SyncFolderValidationResult_val_NonSyncableFolder {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_NonSyncableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SyncFolderValidationResult_val_Succeeded {
            get {
                return ResourceManager.GetString("SyncFolderValidationResult_val_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching updates....
        /// </summary>
        internal static string SyncStatus_val_DetectingUpdates {
            get {
                return ResourceManager.GetString("SyncStatus_val_DetectingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SyncStatus_val_Failed {
            get {
                return ResourceManager.GetString("SyncStatus_val_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        internal static string SyncStatus_val_Idle {
            get {
                return ResourceManager.GetString("SyncStatus_val_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string SyncStatus_val_Initializing {
            get {
                return ResourceManager.GetString("SyncStatus_val_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string SyncStatus_val_Offline {
            get {
                return ResourceManager.GetString("SyncStatus_val_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string SyncStatus_val_Paused {
            get {
                return ResourceManager.GetString("SyncStatus_val_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        internal static string SyncStatus_val_Synchronizing {
            get {
                return ResourceManager.GetString("SyncStatus_val_Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SyncStatus_val_Terminated {
            get {
                return ResourceManager.GetString("SyncStatus_val_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating....
        /// </summary>
        internal static string SyncStatus_val_Terminating {
            get {
                return ResourceManager.GetString("SyncStatus_val_Terminating", resourceCulture);
            }
        }
    }
}
