<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proton.Drive.Shared\Proton.Drive.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="Proton.Drive.Sdk.Sync.Agent" />
    <InternalsVisibleTo Include="Proton.Drive.Sdk.Sync.Agent.Tests" />
  </ItemGroup>

</Project>
