<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\Http\**" />
    <Compile Remove="Extensions\Internal\**" />
    <EmbeddedResource Remove="Extensions\Http\**" />
    <EmbeddedResource Remove="Extensions\Internal\**" />
    <None Remove="Extensions\Http\**" />
    <None Remove="Extensions\Internal\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="ProtonDrive.App.Tests" />
    <InternalsVisibleTo Include="ProtonDrive.App.Windows.Tests" />
    <InternalsVisibleTo Include="ProtonDrive.Client.Tests" />
    <InternalsVisibleTo Include="ProtonDrive.Sync.Adapter.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNext.Threading" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="morelinq" />
  </ItemGroup>

</Project>
