<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="morelinq" />
    <PackageReference Include="Sentry" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtonDrive.Client\ProtonDrive.Client.csproj" />
    <ProjectReference Include="..\ProtonDrive.DataAccess\ProtonDrive.DataAccess.csproj" />
    <ProjectReference Include="..\ProtonDrive.Shared\ProtonDrive.Shared.csproj" />
    <ProjectReference Include="..\ProtonDrive.Sync.Adapter\ProtonDrive.Sync.Adapter.csproj" />
    <ProjectReference Include="..\ProtonDrive.Sync.Agent\ProtonDrive.Sync.Agent.csproj" />
    <ProjectReference Include="..\ProtonDrive.Sync.Engine\ProtonDrive.Sync.Engine.csproj" />
    <ProjectReference Include="..\ProtonDrive.Sync.Shared\ProtonDrive.Sync.Shared.csproj" />
    <ProjectReference Include="..\ProtonDrive.Update\ProtonDrive.Update.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="ProtonDrive.App.Windows.Tests" />
    <InternalsVisibleTo Include="ProtonDrive.Sync.Adapter.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ProtonDrive.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
