<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);Photos</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proton.Drive.Shared\Proton.Drive.Shared.csproj" />
    <ProjectReference Include="..\Proton.Drive.Sdk.Sync.Shared\Proton.Drive.Sdk.Sync.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Proton.Drive.Sdk" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="Proton.Drive.App.Tests" />
    <InternalsVisibleTo Include="Proton.Drive.Sdk.Sync.Agent.Tests" />
  </ItemGroup>

</Project>
